### ISSUE TITLE
R&D - Test React Components

### ISSUE THREAD

**Issue by KrishnaPatel1** [lkadian/WikipediaData#35]
As a member of the R&D team, I would like to be able to unit test the React components in our webapp in order to validate correct uptime of the system.

Tasks:
- [x] Add testing framework to the project
- [x] Create acceptance tests
- [ ] Add test script to CI

Story Points: 5
Ideal Hours: 12
Priority: High
Risk: Low

**Comment by KrishnaPatel1** [comment]
I will not be adding the test script to the CI since Travis will not be running the application during its executing cycle. The application must be running in order to run the acceptance tests

**Comment by anthonyle17** [comment]
> I will not be adding the test script to the CI since Travis will not be running the application during its executing cycle. The application must be running in order to run the acceptance tests

As @KrishnaPatel1 mentioned, this will not be implemented anymore; hence, this issue is completed via this [PR](https://github.com/lkadian/WikipediaData/pull/72).
