### ISSUE TITLE
WEB - Logging Database

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#37]
Create a logging database module with the fields seen below:
* [request time, request ip, request, response]
Apply this logging to each request endpoint, and keep the database off the repository (local only). 

Document it on GitWiki before closing this issue

Parent Issue: #36

Ideal Hours: 2

**Comment by aa-software2112** [comment]
This is complete, waiting on PR [#65]

**Comment by anthonyle17** [comment]
Done via this [PR](https://github.com/lkadian/WikipediaData/pull/65).
