### ISSUE TITLE
WEB/DATA - Revenue DB & Endpoint

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#41]
Create a revenue database with the fields:
*  [ISIN (foreign key), revenue in dollars, reference year, observation year]. Any other metrics are extra.

Create an endpoint for this data:
* given an ISIN, get _all_ revenue rows for that company. 

@laurawheatley @lkadian 
* Fill in DB with real revenue data

Parent Issue: [#39]

Ideal Hours: 6

**Comment by aa-software2112** [comment]
All work in this task is complete, a PR for the work can be found in #54 and the database in our google drive

**Comment by anthonyle17** [comment]
Done via this [PR](https://github.com/lkadian/WikipediaData/pull/54).
