### ISSUE TITLE
WEB - Revenue Front-End

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#42]
Create a revenue front-end that displays revenue for the company on the company page. Should be a single endpoint call to grab all the revenues and display them in a bar graph.

Parent Issue: #39

Ideal Hours: 2.5

**Comment by anthonyle17** [comment]
PR linked to this issue [here](https://github.com/lkadian/WikipediaData/pull/59).

**Comment by anthonyle17** [comment]
Done via this [PR](https://github.com/lkadian/WikipediaData/pull/59).
