### ISSUE TITLE
DATA - Domain, Class Diagram, and Architecture

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#44]
- [x] Create a high-level architecture diagram showing the components of our system (don't go too detailed)

- [x] Since we are not using classes, we just need to update the database schema to reflect the databases we have created (Revenue, company listing, page views, logging)

Ideal Hours: 3
Story Points: 2
Risk: LOW
Priority: LOW

**Comment by Lussier115** [comment]
[Architecture Drive Folder](https://drive.google.com/drive/folders/1KU8ikppGZyzrp9T7w0JVgnrpkvUOjQFI)

**Comment by samgo1** [comment]
done, can be seen [here](https://github.com/lkadian/WikipediaData/wiki/Architecture#architecture-diagram)
