### ISSUE TITLE
DATA - Package Diagram

### ISSUE THREAD

**Issue by aa-software2112** [lkadian/WikipediaData#45]
- [x] The package diagram should describe the file-system organization of our project

Ideal Hours: 2
Story Points: 1
Risk: LOW
Priority: LOW

**Comment by laurawheatley** [comment]
The completed package diagram can be found here: https://www.lucidchart.com/invitations/accept/bae26537-8e11-4f7c-b336-747e75e7e8c9 and in the Milestone 1 release document.
