### ISSUE TITLE
R&D - Create Unit Tests For Endpoints

### ISSUE THREAD

**Issue by KrishnaPatel1** [lkadian/WikipediaData#48]
As an R&D dev, I would like to unit test the endpoints listed below for the backend components, so that we can ensure that the components will correct correctly in the future.

- Revenue
- CEO
- Products
- Industries

Story Points: 3
Ideal Hours: 4
Risk: Low
Priority: High

**Comment by Lussier115** [comment]
Unit Test [Branch](https://github.com/lkadian/WikipediaData/tree/r%26d/unit_test_%2348)

**Comment by anthonyle17** [comment]
All commits related to this issue can be found via this [PR](https://github.com/lkadian/WikipediaData/pull/66).

Issue completed.
