### ISSUE TITLE
WEB/DATA- Company Miscellaneous Properties Endpoints

### ISSUE THREAD

**Issue by anthonyle17** [lkadian/WikipediaData#57]
1. - [x] Create a industry table in database with the fields:

*  [ISIN (foreign key), industry, observation time]. Any other metrics are extra.

2. - [x] Create an endpoint for this data:
* given an ISIN, get all industry rows for that company. 

3. - [x] Create a subsidiaries table in database with the fields:
*  [ISIN (foreign key), assets, observation time]. Any other metrics are extra.

4. - [x] Create an endpoint for this data:
* given an ISIN, get all subsidiaries rows for that company. 

5. - [x] Create a ceos table in database with the fields:
*  [ISIN (foreign key), ceo, reference_start, reference_end, observation time]. Any other metrics are extra.

6. - [x] Create an endpoint for this data:
* given an ISIN, get all ceo rows for that company. 

7. - [x] Create a products or materials produced table in database with the fields:
*  [ISIN (foreign key), product, observation time]. Any other metrics are extra.

8. - [x] Create an endpoint for this data:
* given an ISIN, get all product rows for that company. 

9. - [x] Fill in DB with real data @laurawheatley @lkadian 

Parent Issue: [#55]

Ideal Hours: 7

**Comment by anthonyle17** [comment]
Tables created by @lkadian  in DB:
- ceos
- industries
- products_or_mats_produced 

DB name is wiki-v3.db uploaded [here](https://drive.google.com/drive/folders/1mdgtsr7nq396KNqme_jRx5fElIIRaCw1).

**Comment by lkadian** [comment]
@anthonyle17 Just an update the latest db is wiki-v4.1.db, it contains the tables you listed as well as "subsidiaries"

**Comment by anthonyle17** [comment]
- ceos
- industries
- products_or_mats_produced 
Merged to master via this [PR](https://github.com/lkadian/WikipediaData/pull/60) and this [one](https://github.com/lkadian/WikipediaData/pull/64).

**Comment by anthonyle17** [comment]
- subsidiaries
Merged to master via this [commit](https://github.com/lkadian/WikipediaData/pull/66/commits/4873bb33d262c132bf4dc675fea57603adee6379).
